PROJECT  = new-plugin
GIT_URL  = git@github.com:timlau/audio_spec_files.git

# exclude submodules from source tarball
# GITSUBMODULE_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

