PROJECT = neural-amp-modeler
#GIT_URL = git@github.com:mikeoliphant/neural-amp-modeler-lv2.git 
GIT_URL = git@github.com:timlau/neural-amp-modeler-lv2.git

ROOT = ../common
include $(ROOT)/Makefile.githead.mk