PROJECT  = vst3sdk
GIT_URL  = git@github.com:steinbergmedia/vst3sdk.git
# exclude submodules from source tarball
# GITSUBMODULE_EXCLUDE = 

# Checkout a give git tag
# GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

