PROJECT = dexed
GIT_URL = git@github.com:asb2m10/dexed.git  
# exclude JUCE submodule from source tarball
GITSUBMODULE_EXCLUDE = libs/JUCE
# checkout git tagged version
GIT_TAG = v$(VERSION)

ROOT = ../../common
include $(ROOT)/Makefile.git.mk

